## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.show-sql=true

# Cree les tables si elles n'existent pas mais ne supprime pas les donnees existantes
spring.jpa.hibernate.ddl-auto=update
